name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  postman-newman-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Postman collection
        id: postman-newman-action
        uses: ./
        with:
          collection: "./__tests__/httpbin-collection.json"
          outputGoogleCardV2: true

      - name: Print Output
        id: output
        run: echo "${{ steps.postman-newman-action.outputs.summary }}"
        if: ${{ always() }}

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          additionalSections: '${{ steps.postman-newman-action.outputs.googleCardV2 }}'
          jobStatus: '${{ job.status }}'
          imageUrl: https://user-images.githubusercontent.com/7853266/44114706-9c72dd08-9fd1-11e8-8d9d-6d9d651c75ad.png
          imageAltText: 'Postman Image'

      - name: Run Postman collection 2
        if: ${{ always() }}
        id: postman-newman-action-2
        uses: ./
        with:
          collection: "./__tests__/httpbin-collection.json"
          outputGoogleCardV2: true

      - name: Concat outputGoogleCardV2 output using jq
        if: ${{ always() }}
        id: concat-google-card-v2
        run: |
          CONCATINATED_ARRAY=echo -e "${{ steps.postman-newman-action.outputs.googleCardV2 }}\n${{ steps.postman-newman-action-2.outputs.googleCardV2 }}" | jq -s 'add'
          echo "GOOGLE_CHAT_SECTIONS_ARRAY=$CONCATINATED_ARRAY" >> "$GITHUB_OUTPUT"

      - name: Notify Google Chat
        if: ${{ always() }}
        uses: SimonScholz/google-chat-action@main
        with:
          title: 'Concatenated Google Chat Card'
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          additionalSections: '${{ steps.concat-google-card-v2.outputs.GOOGLE_CHAT_SECTIONS_ARRAY }}'
          jobStatus: '${{ job.status }}'
          imageUrl: https://user-images.githubusercontent.com/7853266/44114706-9c72dd08-9fd1-11e8-8d9d-6d9d651c75ad.png
          imageAltText: 'Postman Image'
